# Generated by Django 5.0.3 on 2024-05-25 09:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpost',
            name='main_phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='listingpost',
            name='mobile_phone',
            field=models.CharField(blank=True, default=2, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingpost',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the property price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
