# Generated by Django 5.0.3 on 2024-05-18 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingamenities',
            options={'ordering': ('title',), 'verbose_name_plural': 'Property Amenties'},
        ),
        migrations.AlterModelOptions(
            name='listingcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Property Categories'},
        ),
        migrations.AlterModelOptions(
            name='listingreview',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Property Reviews'},
        ),
        migrations.AlterModelOptions(
            name='listingsubcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Property SubCategories'},
        ),
        migrations.CreateModel(
            name='PropertyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject of the message', max_length=255)),
                ('message', models.TextField(help_text='Contact Description')),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('listing', models.ForeignKey(help_text='Select the property', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='listing.listingpost')),
                ('user', models.ForeignKey(help_text='Author who created the review', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties Contacts',
                'ordering': ('-submit_date',),
            },
        ),
    ]
