# Generated by Django 5.0.3 on 2024-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listingamenities_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpost',
            name='business_name',
            field=models.CharField(help_text='Enter the property name', max_length=1000, verbose_name='Property name'),
        ),
        migrations.AlterField(
            model_name='listingpost',
            name='price',
            field=models.CharField(help_text='Enter the property price', max_length=255),
        ),
        migrations.AlterField(
            model_name='listingpost',
            name='state',
            field=models.CharField(blank=True, help_text='Enter the province name', max_length=1000, null=True, verbose_name='Province'),
        ),
    ]
