# Generated by Django 5.0.3 on 2024-05-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_listingpost_business_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingcategory',
            name='on_home',
        ),
        migrations.RemoveField(
            model_name='listingpost',
            name='on_home',
        ),
        migrations.RemoveField(
            model_name='listingreview',
            name='status',
        ),
    ]
