# Generated by Django 5.0.3 on 2024-05-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the blog category name', max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the blog title', max_length=500)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('image', models.ImageField(help_text='Upload the blog image (751*422)', upload_to='blog/images')),
                ('body', models.TextField(help_text='Enter the blog body')),
                ('category', models.ForeignKey(help_text='Choose the blog category', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.blogcategory')),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['title', 'updated_at'],
            },
        ),
    ]
