# Generated by Django 5.0.3 on 2024-05-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(help_text='Upload the about hero image (1921*251)', upload_to='about/images')),
                ('side_image', models.ImageField(help_text='Upload the about side image (690*767)', upload_to='about/images')),
                ('footer_image', models.ImageField(help_text='Upload the about footer image (1920*541)', upload_to='about/images')),
                ('about_title', models.CharField(help_text='Enter the about title', max_length=500)),
                ('about_text', models.TextField(help_text='Enter the about description', verbose_name='About description')),
                ('location', models.CharField(help_text='Enter the location', max_length=500)),
                ('latitude', models.CharField(blank=True, help_text='Enter the latitude', max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, help_text='Enter the longitude', max_length=100, null=True)),
                ('email', models.EmailField(help_text='Enter the email', max_length=254)),
                ('phone', models.CharField(help_text='Enter the phone number', max_length=20)),
                ('facebook', models.URLField(blank=True, help_text='Enter the Facebook URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Enter the Instagram URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Enter the X (Formerly Twitter) URL', null=True, verbose_name='X (Formerly Twitter)')),
                ('dribble', models.CharField(blank=True, help_text='Enter the Dribble URL', max_length=500, null=True)),
                ('rss', models.CharField(blank=True, help_text='Enter the RSS URL', max_length=500, null=True)),
                ('vk', models.CharField(blank=True, help_text='Enter the VK URL', max_length=500, null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Enter the LinkedIn URL', null=True)),
                ('skype', models.CharField(blank=True, help_text='Enter the Skype ID', max_length=1000, null=True)),
                ('google_plus', models.CharField(blank=True, help_text='Enter the Google Plus URL', max_length=500, null=True)),
                ('pinterest', models.URLField(blank=True, help_text='Enter the Pinterest URL', null=True)),
                ('about_youtube_url', models.URLField(blank=True, help_text='Enter the Youtube Video URL that you want to show in about section', null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contact Person Name', max_length=1000)),
                ('email', models.EmailField(help_text='Contact Email Address', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=255)),
                ('description', models.TextField(help_text='Contact Description')),
                ('submit_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Enter the FAQ question')),
                ('answer', models.TextField(help_text='Enter the FAQ answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'FAQs',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the page title', max_length=500)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('body', models.TextField(help_text='Enter the page body')),
            ],
            options={
                'verbose_name_plural': 'Pages',
                'ordering': ['title', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('faq', 'FAQ Hero Image (1920*251)'), ('contact', 'Contact Hero Image (1920*251)'), ('blog', 'Blog Hero Image(1920*251)'), ('ad', 'Ad Image(359*560)'), ('home_hero', 'Home Hero Image(1920*890)'), ('home_main', 'Home Main Image(1920*960)'), ('profile_hero', 'Profile Hero Image(1920*251)'), ('add_listing', 'Add Listing Hero Image(1920*251)')], error_messages={'unique': "An image for this place already exists. You can't add two images in one place"}, help_text='Choose the image placement', max_length=20, unique=True)),
                ('image', models.ImageField(help_text='Upload the image', upload_to='decoration/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Images',
            },
        ),
    ]
