# Generated by Django 5.0.3 on 2024-05-22 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='user/cover/default_user.png', help_text='User Profile Picture', null=True, upload_to='user/cover')),
                ('bio', models.TextField(help_text='User description or bio', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='User phone number', max_length=40, null=True)),
                ('website', models.URLField(blank=True, help_text='Enter the website URL', null=True)),
                ('designation', models.CharField(blank=True, help_text='Enter the designation', max_length=1000, null=True)),
                ('company', models.CharField(blank=True, help_text='Enter the company name', max_length=1000, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Enter the Facebook URL', null=True)),
                ('twitter', models.URLField(blank=True, help_text='Enter the Twitter URL', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Enter the LinkedIn URL', null=True)),
                ('skype', models.CharField(blank=True, help_text='Enter the Skype ID', max_length=1000, null=True)),
                ('google_plus', models.URLField(blank=True, help_text='Enter the Google Plus URL', null=True)),
                ('pinterest', models.URLField(blank=True, help_text='Enter the Pinterest URL', null=True)),
                ('user', models.OneToOneField(help_text='User associated with this profile', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
